# Render Blueprint - AlphaStack Trading Platform

databases:
  - name: alphastack-db
    databaseName: alphastack
    user: alphastack
    region: oregon
    plan: basic-1gb
    postgresMajorVersion: "17"

services:
  # Discovery API - Stock Discovery Engine
  - type: web
    name: alphastack-discovery
    runtime: docker
    repo: https://github.com/mikedmote52/daily-trading.git
    rootDir: agents/discovery
    dockerfilePath: Dockerfile
    region: oregon
    plan: free
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: alphastack-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: keyvalue
          name: alphastack-kv
          property: connectionString
      - key: POLYGON_API_KEY
        sync: false
      - key: DISCOVERY_CYCLE_SECONDS
        value: "60"
      - key: TOP_N
        value: "8"
      - key: ENVIRONMENT
        value: production
      - key: RENDER
        value: "true"
      - key: MCP_ENABLED
        value: "true"

  # Orders API - Alpaca Trading Integration
  - type: web
    name: alphastack-orders
    runtime: docker
    repo: https://github.com/mikedmote52/daily-trading.git
    rootDir: agents/backend
    dockerfilePath: Dockerfile
    region: oregon
    plan: free
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: alphastack-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: keyvalue
          name: alphastack-kv
          property: connectionString
      - key: ALPACA_BASE_URL
        value: https://paper-api.alpaca.markets
      - key: ALPACA_KEY
        sync: false
      - key: ALPACA_SECRET
        sync: false
      - key: LIMIT_BAND_PCT
        value: "0.005"
      - key: SL_PCT_DEFAULT
        value: "0.10"
      - key: TP_PCT_DEFAULT
        value: "0.20"
      - key: ENVIRONMENT
        value: production

  # Frontend - React Trading UI
  - type: web
    name: alphastack-frontend
    runtime: static
    repo: https://github.com/mikedmote52/daily-trading.git
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    autoDeploy: true
    envVars:
      - key: VITE_DISCOVERY_API_URL
        value: https://alphastack-discovery.onrender.com
      - key: VITE_ORDERS_API_URL
        value: https://alphastack-orders.onrender.com
      - key: NODE_ENV
        value: production

  # Discovery Worker - Background Processing (CORRECTED)
  - type: worker
    name: amc-discovery-worker
    env: python
    plan: standard
    buildCommand: pip install -r requirements.txt
    startCommand: python -m backend.src.services.rq_worker_main
    autoDeploy: true
    numInstances: 1
    envVars:
      - key: REDIS_URL
        fromService:
          type: keyvalue
          name: alphastack-kv
          property: connectionString
      - key: POLYGON_API_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: alphastack-db
          property: connectionString
      - key: ALPACA_API_KEY
        sync: false
      - key: ALPACA_SECRET_KEY
        sync: false
      - key: ALPACA_BASE_URL
        sync: false
      - key: ENV
        value: prod
      - key: LOG_LEVEL
        value: INFO
      - key: DISCOVERY_CACHE_TTL
        value: "60"

  # Redis-compatible Key Value
  - type: keyvalue
    name: alphastack-kv
    region: oregon
    plan: standard
    maxmemoryPolicy: allkeys-lru
    ipAllowList:
      - source: 0.0.0.0/0
        description: allow all (temp)