# Render Blueprint - AlphaStack Trading Platform

databases:
  - name: alphastack-db
    databaseName: alphastack
    user: alphastack
    region: oregon
    plan: basic-1gb
    postgresMajorVersion: "17"

services:
  # Discovery API - Stock Discovery Engine
  - type: web
    name: alphastack-discovery
    runtime: docker
    repo: https://github.com/mikedmote52/daily-trading.git
    rootDir: agents/discovery
    dockerfilePath: Dockerfile
    region: oregon
    plan: free
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: alphastack-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: keyvalue
          name: alphastack-kv
          property: connectionString
      - key: POLYGON_API_KEY
        sync: false
      - key: DISCOVERY_CYCLE_SECONDS
        value: "60"
      - key: TOP_N
        value: "8"
      - key: ENVIRONMENT
        value: production
      - key: RENDER
        value: "true"
      - key: MCP_ENABLED
        value: "true"

  # Orders API - Alpaca Trading Integration
  - type: web
    name: alphastack-orders
    runtime: docker
    repo: https://github.com/mikedmote52/daily-trading.git
    rootDir: agents/backend
    dockerfilePath: Dockerfile
    region: oregon
    plan: free
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: alphastack-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: keyvalue
          name: alphastack-kv
          property: connectionString
      - key: ALPACA_BASE_URL
        value: https://paper-api.alpaca.markets
      - key: ALPACA_KEY
        sync: false
      - key: ALPACA_SECRET
        sync: false
      - key: LIMIT_BAND_PCT
        value: "0.005"
      - key: SL_PCT_DEFAULT
        value: "0.10"
      - key: TP_PCT_DEFAULT
        value: "0.20"
      - key: ENVIRONMENT
        value: production

  # Portfolio API - Portfolio Management
  - type: web
    name: alphastack-portfolio
    runtime: docker
    repo: https://github.com/mikedmote52/daily-trading.git
    rootDir: agents/portfolio
    dockerfilePath: Dockerfile
    region: oregon
    plan: free
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: alphastack-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: keyvalue
          name: alphastack-kv
          property: connectionString
      - key: ALPACA_BASE_URL
        value: https://paper-api.alpaca.markets
      - key: ALPACA_KEY
        sync: false
      - key: ALPACA_SECRET
        sync: false
      - key: CLAUDE_API_KEY
        sync: false
      - key: ENVIRONMENT
        value: production

  # Frontend - MCP-Enhanced Trading UI
  - type: static
    name: alphastack-frontend-mcp
    repo: https://github.com/mikedmote52/daily-trading.git
    rootDir: frontend
    # Vite build system
    buildCommand: npm install && npm run build
    publishPath: dist
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: "20"
      - key: NPM_CONFIG_PRODUCTION
        value: "false"
      - key: VITE_ORDERS_API_URL
        value: "https://alphastack-orders.onrender.com"
      - key: VITE_DISCOVERY_API_URL
        value: "https://alphastack-discovery.onrender.com"
      - key: VITE_MCP_DISCOVERY_URL
        value: "https://alphastack-discovery.onrender.com"
      - key: VITE_PORTFOLIO_API_URL
        value: "https://alphastack-portfolio.onrender.com"
    routes:
      - type: rewrite
        source: "/*"
        destination: "/index.html"

  # Redis-compatible Key Value
  - type: keyvalue
    name: alphastack-kv
    region: oregon
    plan: standard
    maxmemoryPolicy: allkeys-lru
    ipAllowList:
      - source: 0.0.0.0/0
        description: allow all (temp)